In [1]:
# import necessary library 
import warnings
warnings.filterwarnings('ignore')
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt


In [2]:
# import data 
df= pd.read_csv("winequality_red.csv")
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [3]:
df.shape

(1599, 12)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [5]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1599.000000       1599.000000  1599.000000     1599.000000   
mean        8.319637          0.527821     0.270976        2.538806   
std         1.741096          0.179060     0.194801        1.409928   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.390000     0.090000        1.900000   
50%         7.900000          0.520000     0.260000        2.200000   
75%         9.200000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1599.000000          1599.000000           1599.000000  1599.000000   
mean      0.087467            15.874922             46.467792     0.996747   
std       0.047065            10.460157             32.895324     0.001887   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             22.000000     0.995600   
50%       0.079000            14.000000             38.000000     0.996750   
75%       0.090000            21.000000             62.000000     0.997835   
max       0.611000            72.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality  
count  1599.000000  1599.000000  1599.000000  1599.000000  
mean      3.311113     0.658149    10.422983     5.636023  
std       0.154386     0.169507     1.065668     0.807569  
min       2.740000     0.330000     8.400000     3.000000  
25%       3.210000     0.550000     9.500000     5.000000  
50%       3.310000     0.620000    10.200000     6.000000  
75%       3.400000     0.730000    11.100000     6.000000  
max       4.010000     2.000000    14.900000     8.000000

# Preprocessing The Data

In [6]:
# Check missing value in data 
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

There is no missing value in data

In [7]:
# make copy of the original dataset 
data=pd.DataFrame.copy(df)

In [8]:
# Create x and y
x=data.drop(columns='quality')
y=data['quality']

In [9]:
x.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  
0      9.4  
1      9.8  
2      9.8  
3      9.8  
4      9.4

In [10]:
y.head()

0    5
1    5
2    5
3    6
4    5
Name: quality, dtype: int64

In [11]:
# Splitting the data into train and test 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=10)

In [12]:
# build the model
from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier()
clf.fit(x_train,y_train)    

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [13]:
#predict the model
y_pred=clf.predict(x_test)
print(y_pred)

[6 5 6 6 6 7 4 6 3 5 7 3 5 5 6 5 5 6 6 5 5 7 7 5 6 6 5 6 6 5 6 6 6 7 5 5 7
 5 6 5 6 6 5 6 5 4 6 7 7 7 5 7 6 7 6 7 6 5 5 5 6 5 7 5 6 5 6 6 6 6 6 5 5 5
 5 5 5 7 5 7 7 5 7 5 6 5 6 5 5 5 7 5 7 6 5 6 5 5 7 5 7 5 5 6 5 6 6 6 6 5 5
 7 7 5 6 5 5 5 6 6 5 5 6 5 5 4 5 5 5 5 6 6 6 4 6 7 7 5 5 7 6 6 7 5 6 6 7 5
 6 6 6 6 6 7 5 5 5 3 5 7 6 6 7 5 5 4 6 7 7 5 5 5 6 6 5 5 6 6 5 8 5 6 6 5 5
 5 5 6 5 5 5 4 6 7 6 5 3 5 7 6 6 5 5 6 5 5 6 5 5 7 6 5 4 5 5 6 5 5 5 5 5 6
 6 5 6 5 6 5 5 5 4 6 6 6 5 6 5 5 5 5 6 5 5 6 6 5 5 4 5 5 5 6 5 5 5 6 7 7 7
 7 5 6 6 5 5 5 6 6 6 6 5 6 5 6 4 6 5 5 6 5 6 6 6 7 4 6 6 6 5 5 7 5 5 7 5 7
 6 5 5 6 6 6 6 6 6 7 6 6 6 5 5 6 6 7 6 7 5 7 5 5]


In [14]:
# make list of zip of actual output with predicted output
print(list(zip(y_test,y_pred)))

[(5, 6), (5, 5), (6, 6), (6, 6), (5, 6), (6, 7), (7, 4), (6, 6), (5, 3), (5, 5), (7, 7), (4, 3), (5, 5), (5, 5), (6, 6), (5, 5), (6, 5), (6, 6), (6, 6), (5, 5), (5, 5), (6, 7), (5, 7), (5, 5), (5, 6), (5, 6), (5, 5), (6, 6), (6, 6), (6, 5), (5, 6), (5, 6), (7, 6), (8, 7), (5, 5), (5, 5), (8, 7), (6, 5), (6, 6), (6, 5), (6, 6), (7, 6), (5, 5), (7, 6), (5, 5), (7, 4), (6, 6), (7, 7), (6, 7), (5, 7), (6, 5), (7, 7), (6, 6), (6, 7), (6, 6), (6, 7), (6, 6), (5, 5), (5, 5), (5, 5), (5, 6), (5, 5), (7, 7), (6, 5), (6, 6), (5, 5), (6, 6), (6, 6), (5, 6), (6, 6), (6, 6), (5, 5), (5, 5), (6, 5), (6, 5), (5, 5), (5, 5), (7, 7), (5, 5), (7, 7), (7, 7), (5, 5), (6, 7), (5, 5), (6, 6), (4, 5), (4, 6), (5, 5), (5, 5), (5, 5), (6, 7), (5, 5), (7, 7), (6, 6), (5, 5), (4, 6), (5, 5), (4, 5), (5, 7), (6, 5), (7, 7), (5, 5), (6, 5), (6, 6), (6, 5), (5, 6), (5, 6), (6, 6), (6, 6), (5, 5), (5, 5), (6, 7), (7, 7), (5, 5), (5, 6), (5, 5), (5, 5), (5, 5), (8, 6), (5, 6), (5, 5), (5, 5), (6, 6), (5, 5), (5, 5),

# Check accuracy of the model

In [15]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification Report:')
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print(acc)

[[ 0  2  0  0  0  0]
 [ 1  1  4  3  0  0]
 [ 2  2 97 25  6  0]
 [ 0  4 32 71 19  1]
 [ 1  2  7 13 19  0]
 [ 0  0  0  4  4  0]]
classification Report:
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.09      0.11      0.10         9
           5       0.69      0.73      0.71       132
           6       0.61      0.56      0.58       127
           7       0.40      0.45      0.42        42
           8       0.00      0.00      0.00         8

    accuracy                           0.59       320
   macro avg       0.30      0.31      0.30       320
weighted avg       0.58      0.59      0.58       320

0.5875


In [16]:
print(list(zip(data.columns,clf.feature_importances_ )))

[('fixed acidity', 0.05698749591846014), ('volatile acidity', 0.11435512120340117), ('citric acid', 0.048596906874621315), ('residual sugar', 0.07144242745346399), ('chlorides', 0.08894643907193453), ('free sulfur dioxide', 0.04142907290927111), ('total sulfur dioxide', 0.11017565168711255), ('density', 0.0801701873495723), ('pH', 0.10974189897725921), ('sulphates', 0.11775353874851888), ('alcohol', 0.16040125980638498)]


In [17]:
feature_name=list(data.columns[:-1])
class_name = list(y_train.unique())
feature_name

['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol']

In [18]:
# Create file and uplod the code on webgraphviz.com to plot the decision tree
from sklearn import tree
with open ("wine_quality.txt","w") as f:
    f=tree.export_graphviz(clf,feature_names=data.columns[:-1],out_file=f)

# Running ExtraTree Classfier model

In [19]:
# predicting using the bagging Classifier 
from sklearn.ensemble import ExtraTreesClassifier
bagging_model=ExtraTreesClassifier(n_estimators=10,random_state=10)
bagging_model.fit(x_train,y_train)



ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
                     max_depth=None, max_features='auto', max_leaf_nodes=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
                     oob_score=False, random_state=10, verbose=0,
                     warm_start=False)

In [20]:
#Predict the model 
y_pred=bagging_model.predict(x_test)

In [21]:
#check accuracy score of the model
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print("classification Report:")
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print(acc)

[[  0   0   2   0   0   0]
 [  0   0   5   4   0   0]
 [  0   0 112  18   2   0]
 [  0   1  38  78  10   0]
 [  0   0   4  21  17   0]
 [  0   0   0   5   3   0]]
classification Report:
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00         9
           5       0.70      0.85      0.76       132
           6       0.62      0.61      0.62       127
           7       0.53      0.40      0.46        42
           8       0.00      0.00      0.00         8

    accuracy                           0.65       320
   macro avg       0.31      0.31      0.31       320
weighted avg       0.60      0.65      0.62       320

0.646875


In [22]:
#predicting using the random_Forest_classifier 
from sklearn.ensemble import RandomForestClassifier
model_randomForest=RandomForestClassifier(n_estimators=101,random_state=10)
model_randomForest.fit(x_train,y_train)

#predict the model
y_pred=model_randomForest.predict(x_test) 

In [23]:
#check accuracy score of the model
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print("classification Report:")
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print(acc)

[[  0   1   1   0   0   0]
 [  0   0   6   3   0   0]
 [  0   0 105  25   2   0]
 [  0   1  25  95   6   0]
 [  0   0   2  20  20   0]
 [  0   0   0   4   4   0]]
classification Report:
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00         9
           5       0.76      0.80      0.77       132
           6       0.65      0.75      0.69       127
           7       0.62      0.48      0.54        42
           8       0.00      0.00      0.00         8

    accuracy                           0.69       320
   macro avg       0.34      0.34      0.33       320
weighted avg       0.65      0.69      0.67       320

0.6875


In [24]:
#Predicting using adaboost classifier 
from sklearn.ensemble import AdaBoostClassifier
model_adaBoost=AdaBoostClassifier(base_estimator=DecisionTreeClassifier(random_state=10),
                                  n_estimators=10,random_state=10)
model_adaBoost.fit(x_train,y_train)
y_pred=model_adaBoost.predict(x_test)

In [25]:
#check accuracy score of the model
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print("classification Report:")
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print(acc)

[[  0   2   0   0   0   0]
 [  1   1   5   2   0   0]
 [  1   4 102  20   5   0]
 [  0   3  32  75  14   3]
 [  0   2   7  13  20   0]
 [  0   0   0   4   3   1]]
classification Report:
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.08      0.11      0.10         9
           5       0.70      0.77      0.73       132
           6       0.66      0.59      0.62       127
           7       0.48      0.48      0.48        42
           8       0.25      0.12      0.17         8

    accuracy                           0.62       320
   macro avg       0.36      0.35      0.35       320
weighted avg       0.62      0.62      0.62       320

0.621875


In [26]:
#Predicting using Gardient Boosting Classifier
from sklearn.ensemble import GradientBoostingClassifier
model_Gradientboosting=GradientBoostingClassifier(n_estimators=10,random_state=10)
model_Gradientboosting.fit(x_train,y_train)

#predict the model 
y_pred=model_Gradientboosting.predict(x_test)

In [27]:
#check accuracy of the model
from sklearn.metrics import confusion_matrix ,accuracy_score,classification_report
# Confusion matrix
cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print("Classification Report :")
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print(acc)

[[ 0  0  1  1  0  0]
 [ 0  0  5  4  0  0]
 [ 2  1 91 38  0  0]
 [ 2  1 37 84  3  0]
 [ 0  0  3 31  8  0]
 [ 0  0  0  6  2  0]]
Classification Report :
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00         9
           5       0.66      0.69      0.68       132
           6       0.51      0.66      0.58       127
           7       0.62      0.19      0.29        42
           8       0.00      0.00      0.00         8

    accuracy                           0.57       320
   macro avg       0.30      0.26      0.26       320
weighted avg       0.56      0.57      0.55       320

0.571875


# Ensemble Techinque

In [28]:
#Scaling the data 
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x)
x=scaler.transform(x)

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier

In [30]:
# Create the submodels:
estimator=[]
model1=LogisticRegression()
estimator.append(('log',model1))
model2=DecisionTreeClassifier(criterion='gini',random_state=10)
estimator.append(('cart',model2))
#model3=SVC(kernel='rbf',C=50,gamma=0.1)
#estimator.append(('svm',model3))
#model4=KNeighborsClassifier(n_neighbors=8,metric='euclidean')
#estimator.append(('knn',model4))
model5=ExtraTreesClassifier(n_estimators=10,random_state=10)
estimator.append(('extratree',model5))
model6=AdaBoostClassifier(base_estimator=DecisionTreeClassifier(random_state=10),
                                  n_estimators=10,random_state=10)
estimator.append(('Ada',model6))
model7=RandomForestClassifier(n_estimators=101,random_state=10)
estimator.append(('random',model7))
#model8=GradientBoostingClassifier(n_estimators=10,random_state=10)
#estimator.append(('Gradient',model8))




#create the ensemble model
ensemble=VotingClassifier(estimator)
ensemble.fit(x_train,y_train)
y_p=ensemble.predict(x_test)
print(y_p)

[6 5 6 6 6 6 6 6 3 5 7 5 5 5 6 5 6 6 6 5 5 6 6 5 5 6 5 6 6 5 5 5 6 7 5 5 7
 5 6 5 6 6 5 6 5 6 5 7 7 5 6 7 6 7 6 6 6 5 5 5 6 5 7 6 6 5 6 6 5 6 6 5 5 5
 5 5 5 7 5 7 7 5 6 5 6 6 6 5 5 5 6 5 7 6 5 4 5 5 6 6 7 5 5 6 6 6 5 6 6 5 5
 6 7 5 5 5 5 5 6 6 5 5 6 5 5 4 5 5 5 5 6 5 5 4 6 6 6 5 5 7 6 6 5 5 6 6 6 5
 6 6 5 6 6 7 5 5 5 5 6 7 6 6 6 5 6 6 6 7 6 5 5 6 6 6 6 5 5 5 5 6 6 6 6 5 5
 5 5 6 5 5 5 5 6 7 6 5 5 5 7 6 6 5 5 6 5 5 5 5 5 7 6 6 4 5 5 6 6 5 5 5 5 6
 5 5 6 5 6 5 5 5 5 6 6 6 5 6 5 5 5 5 6 5 5 6 6 5 5 6 5 6 5 6 5 5 5 6 7 7 7
 6 5 5 6 5 5 5 6 6 6 6 5 6 6 6 5 6 5 5 6 5 6 6 6 7 4 5 5 6 5 6 6 5 6 6 5 7
 6 6 5 6 6 6 6 6 6 7 5 6 6 5 5 5 6 6 6 6 5 7 5 5]


In [31]:
#check accuracy of the model
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
cfm=confusion_matrix(y_test,y_p)
print(cfm)

print("Classification Report:")
print(classification_report(y_test,y_p))

acc=accuracy_score(y_test,y_p)
print(acc)

[[  0   1   1   0   0   0]
 [  0   1   6   2   0   0]
 [  1   1 111  17   2   0]
 [  0   2  28  93   4   0]
 [  0   0   3  21  18   0]
 [  0   0   0   4   4   0]]
Classification Report:
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         2
           4       0.20      0.11      0.14         9
           5       0.74      0.84      0.79       132
           6       0.68      0.73      0.70       127
           7       0.64      0.43      0.51        42
           8       0.00      0.00      0.00         8

    accuracy                           0.70       320
   macro avg       0.38      0.35      0.36       320
weighted avg       0.67      0.70      0.68       320

0.696875


In [32]:
# save model into pickle format
import pickle
with open('WineModelForPrediction.sav','wb')as f:
    pickle.dump(clf,f)
    
with open('BaggingModelForPrediction.sav','wb')as f:
    pickle.dump(bagging_model,f) 
    
with open('RandomForestModelForPrediction.sav','wb')as f:
    pickle.dump(model_randomForest,f)  
    
with open('AdaBoostlModelForPrediction.sav','wb')as f:
    pickle.dump(model_adaBoost,f) 

with open('GradientboostingModelForPrediction.sav','wb')as f:
    pickle.dump(model_Gradientboosting,f) 
    
with open('EnsembleModelForPrediction.sav','wb')as f:
    pickle.dump(ensemble,f)    
 
    
with open('WinestandardScaler.sav','wb')as f :
    pickle.dump(scaler,f)

In [33]:
y_pred=clf.predict([[11.2,0.28,0.56,1.9,0.075,17,60,0.998,3.16,0.58,9.8]])
y_pred

array([6], dtype=int64)

In [34]:
y_pred=bagging_model.predict([[11.2,0.28,0.56,1.9,0.075,17,60,0.998,3.16,0.58,9.8]])
y_pred

array([6], dtype=int64)

In [35]:
y_pred=model_randomForest.predict([[11.2,0.28,0.56,1.9,0.075,17,60,0.998,3.16,0.58,9.8]])
y_pred

array([6], dtype=int64)

In [36]:
y_pred=model_adaBoost.predict([[8.5,0.28,0.56,1.8,0.092,35,103,0.9969,3.3,0.75,10.5]])
y_pred

array([5], dtype=int64)

In [37]:
y_pred=model_Gradientboosting.predict([[8.5,0.28,0.56,1.8,0.092,35,103,0.9969,3.3,0.75,10.5]])
y_pred

array([5], dtype=int64)

In [38]:
y_pred=ensemble.predict([[11.2,0.28,0.56,1.9,0.075,17,60,0.998,3.16,0.58,9.8]])
y_pred

array([6], dtype=int64)